config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  resources :providers do
    resources :trackings
  end

  get 'my_profile' => 'profile#edit', as: :my_profile
  patch 'my_profile' => 'profile#update', as: :update_my_profile
  patch 'my_profile/api_token' => 'profile#recreate_api_token', as: :recreate_api_token

  namespace :api do
    namespace :v1 do
      resources :providers, only: [] do
        resources :trackings, only: %i(create)
      end

      resources :trackings, only: [], param: :code do
        patch :convert, on: :member
      end
    end
  end

  root 'providers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/provider.rb
class Provider < ApplicationRecord
  # ==========================================================
  # Validations
  # ==========================================================
  validates :name, presence: true

  # ==========================================================
  # Relations
  # ==========================================================
  has_many :trackings, dependent: :destroy
end

app/models/tracking.rb
class Tracking < ApplicationRecord
  # ==========================================================
  # Validations
  # ==========================================================
  validates :name, presence: true

  # ==========================================================
  # Relations
  # ==========================================================
  belongs_to :provider

  # ==========================================================
  # Callbacks
  # ==========================================================
  after_initialize :assign_code

  private

  def assign_code
    self.code ||= SecureRandom.uuid
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :confirmable

  # ==========================================================
  # Callbacks
  # ==========================================================
  after_initialize :assign_api_token

  def refresh_api_token
    self.update(api_token: SecureRandom.uuid)
  end

  private

  def assign_api_token
    self.api_token ||= SecureRandom.uuid
  end
end

app/controllers/api/v1/base_controller.rb
module Api
  module V1
    class BaseController < ApplicationController
      skip_before_action :verify_authenticity_token
      skip_before_action :authenticate_user!
      before_action :authenticate_user_from_token!

      #
      # The user should be authenticated passing its API Token
      # in the request's header, with the format:
      # auth_token: <api_token>
      #
      def authenticate_user_from_token!
        auth_token = request.headers['HTTP_AUTH_TOKEN'].presence
        user = User.find_by(api_token: auth_token)

        if user && auth_token
          sign_in user
        elsif auth_token
          render json: {
            query: false,
            error: 'There aren\'t any user with this Auth Token'
          }, status: 401
        else
          render json: {
            query: false,
            error: 'You must specify the auth_token to use API'
          }, status: 401
        end
      end
    end
  end
end

app/controllers/api/v1/trackings_controller.rb
module Api
  module V1
    class TrackingsController < Api::V1::BaseController
      before_action :set_provider, only: :create
      before_action :set_tracking, only: :convert

      def create
        tracking = @provider.trackings.build(tracking_params)

        if tracking.save
          render json: tracking, status: :ok
        else
          render json: { error: { code: 422, message: tracking.errors } }, status: :unprocessable_entity
        end
      end

      def convert
        if @tracking.update(validated: true)
          render json: @tracking, status: :ok
        else
          render json: { error: { code: 422, message: tracking.errors } }, status: :unprocessable_entity
        end
      end

      private

      def set_provider
        @provider = Provider.find(params[:provider_id])
      end

      def set_tracking
        @tracking = Tracking.find_by(code: params[:code])
      end

      def tracking_params
        params.permit(:name)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :set_user

  def edit
  end

  def update
    if @user.update(user_params)
      # Sign in the user by passing validation in case their password changed
      bypass_sign_in(@user)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def recreate_api_token
    @user.update(api_token: SecureRandom.uuid)
    redirect_to my_profile_path
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: %i(edit update destroy)

  def index
    @providers = Provider.includes(:trackings).all
  end

  def new
    @provider = Provider.new
  end

  def create
    @provider = Provider.new(provider_params)

    if @provider.save
      redirect_to providers_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @provider.update(provider_params)
      redirect_to providers_path
    else
      render :edit
    end
  end

  def destroy
    @provider.destroy
    redirect_to providers_path
  end

  private

  def set_provider
    @provider = Provider.find(params[:id])
  end

  def provider_params
    params.require(:provider).permit(:name, :description)
  end
end

app/controllers/trackings_controller.rb
class TrackingsController < ApplicationController
  before_action :set_provider, only: %i(index destroy)
  before_action :set_tracking, only: :destroy

  def index
    @trackings = @provider.trackings
  end

  def destroy
    @tracking.destroy
    redirect_to provider_trackings_path(@provider)
  end

  private

  def set_provider
    @provider = Provider.find(params[:provider_id])
  end

  def set_tracking
    @tracking = Tracking.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  layout 'session'
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'session'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Tracking Pixels</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Providers', providers_path, class: 'nav-link' %>
      </li>
    </ul>
    <%= link_to 'My Profile', my_profile_path, class: 'nav-link' %>
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrackingPixels</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracking Pixels</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="session wrapper fadeInDown">
      <div id="formContent">
        <div class="fadeIn first">
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>">
              <a href="#" data-dismiss="alert" ></a>
              <ul style="list-style-type: none">
                <li>
                  <% if key == "alert"%>
                  <div class="alert alert-danger alert-dismissible">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong> <%= value %></strong>
                  </div>
                  <% end %>
                </li>
              </ul>
            </div>
          <% end %>
        </div>

        <%= yield %>

      </div>
    </div>
  </body>
</html>

app/views/providers/_form.html.erb
<%= simple_form_for @provider do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.button :submit, class: 'btn btn-primary float-right' %>
<% end %>

app/views/providers/_provider.html.erb
<tr class="row m-0">
  <td class="d-inline-block col-1"><%= provider.id %></td>
  <td class="d-inline-block col-3"><%= provider.name %></td>
  <td class="d-inline-block col-5"><%= provider.description %></td>
  <td class="d-inline-block col-1"><%= link_to provider.trackings.size, provider_trackings_path(provider) %></td>
  <td class="d-inline-block col-1"><%= link_to 'Edit', edit_provider_path(provider), class: 'btn btn-primary' %></td>
  <td class="d-inline-block col-1"><%= link_to 'Destroy', provider_path(provider), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/providers/edit.html.erb
<h2>Edit Provider <%= @provider.name %></h2>

<%= render partial: 'form' %>

app/views/providers/index.html.erb
<h2>Providers</h2>

<div class="row mb-4">
  <div class="col-md-1 offset-md-11">
    <%= link_to 'New', new_provider_path, class: 'btn btn-primary' %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table">
      <thead>
        <tr class="row m-0">
          <th class="d-inline-block col-1">#</th>
          <th class="d-inline-block col-3">Name</th>
          <th class="d-inline-block col-5">Description</th>
          <th class="d-inline-block col-1">Trackings</th>
          <th class="d-inline-block col-1"></th>
          <th class="d-inline-block col-1"></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'provider', collection: @providers %>
      </tbody>
    </table>
  </div>
</div>

app/views/providers/new.html.erb
<h2>New Provider</h2>

<%= render partial: 'form' %>

app/views/trackings/_tracking.html.erb
<tr class="row m-0">
  <td class="d-inline-block col-4"><%= tracking.name %></td>
  <td class="d-inline-block col-4"><%= tracking.code %></td>
  <td class="d-inline-block col-3"><%= tracking.validated ? 'Yes' : 'No' %></td>
  <td class="d-inline-block col-1"><%= link_to 'Destroy', provider_tracking_path(tracking.provider, tracking), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/trackings/index.html.erb
<h2>Trackings for <%= @provider.name %></h2>

<div class="row">
  <div class="col-md-12">
    <table class="table">
      <thead>
        <tr class="row m-0">
          <th class="d-inline-block col-4">Name</th>
          <th class="d-inline-block col-4">Code</th>
          <th class="d-inline-block col-3">Validated</th>
          <th class="d-inline-block col-1"></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'tracking', collection: @trackings %>
      </tbody>
    </table>
  </div>
</div>